version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: heladeria
      MYSQL_USER: heladeria_user
      MYSQL_PASSWORD: heladeria_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - heladeria_network  # Agregamos una red compartida

networks:
  heladeria_network:
    driver: bridge  # Red en modo puente para permitir conexión entre equipos

volumes:
  mysql_data:
